baseURL: "https://sobatorinanban.github.io/"
canonifyurls: true
title: "sobatorinanban.github.io"
paginate: 5
theme: "hugo-astatine-theme"
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

preserveTaxonomyNames: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 鶏南蛮そば
  description: "Portfolio and blog of me, Soba Torinanban, a student of Computer Science."
  keywords: [Blog, Portfolio, PaperMod, Computer Science, Student, Engineer]
  authorName: "Soba Torinanban"
  author: "Soba Torinanban"
  twitter:
    name: "@soba_torinanban"
  # author: ["Me", "You"] # multiple authors
  imgname: 
    name: "/img/main.jpg"
    alt: "Profile picture" 
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # #austatine
  # blogrss: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/myicon.png"
    favicon16x16: "/img/myicon.png"
    favicon32x32: "/img/myicon.png"
    apple_touch_icon: "/img/myicon.png"
    safari_pinned_tab: "/img/myicon.png"
    disableFingerprinting: true
    
  label:
    text: "sobatorinanban.github.io"
    #icon: /.png
    #iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: 鶏南蛮そば
  #   subtitle: "I'm a college student of Computer Science."
  #   imageUrl: "/img/myicon.png"
  #   imageWidth: 120  #120
  #   imageHeight: 120 #120
  #   imageTitle: my icon
  #   buttons:
  #     - name: Archives
  #       url: /archives/

  # home-info mode
  #homeInfoParams:
  #  Title: "Hi there \U0001F44B"
  #  Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/soba_torinanban"
    #- name: stackoverflow
    #  url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/sobatorinanban"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/sobatorinanban/sobatorinanban.github.io/commits/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 5
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 15
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
pygmentsCodefences: true
pygmentsStyle: "native"
#austatine
taxonomies:
  category: "categories"
  tag: "tags"
permalinks:
  posts: /posts/:year/:month/:day/:slug/
